apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: 'true'
objects:
  - apiVersion: v1
    stringData:
      NEXT_SERVER_URL: ${NEXT_SERVER_URL}
      NEXT_REDIRECT_URI: ${NEXT_REDIRECT_URI}
    kind: Secret
    metadata:
      name: bcat-client-${ENV}
    type: Opaque
parameters:
  - description: Server Url
    displayName: NEXT_SERVER_URL
    name: NEXT_SERVER_URL
    required: true
    value: ''
  - description: Redirect Url
    displayName: NEXT_REDIRECT_URI
    name: NEXT_REDIRECT_URI
    required: false
    value: ''
  - description: Environment (dev, test, prod)
    displayName: ENV
    name: ENV
    required: true
    value: 'dev'
