apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - apiVersion: v1
    stringData:
      CHEFS_INFRASTRUCTURE_FORM_ID: ${CHEFS_INFRASTRUCTURE_FORM_ID}
      CHEFS_NETWORK_FORM_ID: ${CHEFS_NETWORK_FORM_ID}
      CHEFS_INFRASTRUCTURE_API_KEY: ${CHEFS_INFRASTRUCTURE_API_KEY}
      CHEFS_NETWORK_API_KEY: ${CHEFS_NETWORK_API_KEY}
    kind: Secret
    metadata:
      name: chefs-keys-${ENV}
    type: Opaque
parameters:
  - description: Id of Infrastructure form
    displayName: CHEFS_INFRASTRUCTURE_FORM_ID
    name: CHEFS_INFRASTRUCTURE_FORM_ID
    required: true
    value: ""
  - description: Id of Network form
    displayName: CHEFS_NETWORK_FORM_ID
    name: CHEFS_NETWORK_FORM_ID
    required: true
    value: ""
  - description: Api key for CHEFS Infrastructure form
    displayName: CHEFS_INFRASTRUCTURE_API_KEY
    name: CHEFS_INFRASTRUCTURE_API_KEY
    required: true
    value: ""
  - description: Api key for CHEFS Network form
    displayName: CHEFS_NETWORK_API_KEY
    name: CHEFS_NETWORK_API_KEY
    required: true
    value: ""
  - description: Environment (dev, test, prod)
    displayName: ENV
    name: ENV
    required: true
    value: "dev"
