apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${PROJECT_NAME}
labels:
  template: api-deploy
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: true
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 1
          maxUnavailable: 1
          timeoutSeconds: 3600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            deploymentconfig: ${NAME}${SUFFIX}
        spec:
          containers:
            - image: ${NAME}:${VERSION}
              name: api
              env:
                - name: POSTGRES_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: bcat-db-${ENV}
                      key: database-user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bcat-db-${ENV}
                      key: database-password
                - name: POSTGRES_DATABASE
                  value: ${DB_NAME}
                - name: POSTGRES_HOST
                  value: bcat-db-dev
                - name: POSTGRES_PORT
                  value: '5432'
                - name: APP_PORT
                  value: '8080'
                - name: KC_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      key: CLIENT_SSO_HOST
                      name: sso-configs-${ENV}
                - name: KC_AUTH_REALM
                  valueFrom:
                    secretKeyRef:
                      key: CLIENT_SSO_REALM
                      name: sso-configs-${ENV}
                - name: KC_AUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: CLIENT_SSO_CLIENTID
                      name: sso-configs-${ENV}
                - name: INFRASTRUCTURE_FORM
                  valueFrom:
                    secretKeyRef:
                      key: CHEFS_INFRASTRUCTURE_FORM_ID
                      name: chefs-keys-${ENV}
                - name: NETWORK_FORM
                  valueFrom:
                    secretKeyRef:
                      key: CHEFS_NETWORK_FORM_ID
                      name: chefs-keys-${ENV}
                - name: CHEFS_INFRASTRUCTURE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: CHEFS_INFRASTRUCTURE_API_KEY
                      name: chefs-keys-${ENV}
                - name: CHEFS_NETWORK_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: CHEFS_NETWORK_API_KEY
                      name: chefs-keys-${ENV}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU}
                  memory: ${MEMORY}
                limits:
                  cpu: ${CPU}
                  memory: ${MEMORY}
              livenessProbe:
                httpGet:
                  path: /api/v1/version
                  port: 8080
                initialDelaySeconds: 15
                timeoutSeconds: 5
                periodSeconds: 10
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - api
            from:
              kind: ImageStreamTag
              name: ${NAME}:${VERSION}
          type: ImageChange
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        haproxy.router.openshift.io/timeout: 5m
      creationTimestamp: null
      name: ${NAME}-${ENV}
    spec:
      host: api-${HOST}
      path: '/'
      port:
        targetPort: web
      tls:
        termination: edge
      to:
        kind: Service
        name: ${NAME}${SUFFIX}
        weight: 100
      wildcardPolicy: None
parameters:
  - description: Name of the project
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: 'bcat'
  - description: The name assigned to all of the OpenShift resources associated with this config
    displayName: Name
    name: NAME
    required: true
    value: 'api'
  - description: Database name
    displayName: DB_NAME
    name: DB_NAME
    required: false
    value: 'bcat'
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: '-dev'
  - description: Environment short name (dev,test,uat,prod)
    displayName: ENV
    name: ENV
    required: false
    value: 'dev'
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: false
    value: 'v1.0.0'
  - description: HOST
    displayName: HOST
    name: HOST
    required: false
    value: ''
  - description: CPU request
    displayName: CPU
    name: CPU
    required: false
    value: '250m'
  - description: Memory request
    displayName: MEMORY
    name: MEMORY
    required: false
    value: '1.5Gi'
  - description: Port the server will be exposed on
    displayName: Server port
    name: SERVER_PORT
    required: false
    value: '8080'
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: ''
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: ''
