apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${PROJECT_NAME}
labels:
  template: client-build
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: "true"
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      completionDeadlineSeconds: 600
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      resources:
        limits:
          cpu: ${CPU}
          memory: ${MEMORY}
        requests:
          cpu: ${CPU}
          memory: ${MEMORY}
      postCommit: {}
      source:
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        type: Git
        contextDir: client
      strategy:
        type: Docker
parameters:
  - description: Name of the project (BCAT)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "bcat"
  - description: The name assigned to all of the OpenShift resources associated with this config
    displayName: Name
    name: NAME
    required: true
    value: "client"
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "dev"
  - description: A version used for the image tags
    displayName: Version
    name: VERSION
    required: false
    value: "v1.0.0"
  - description: CPU
    displayName: CPU request
    name: CPU
    required: false
    value: "100m"
  - description: MEMORY
    displayName: Memory request
    name: MEMORY
    required: false
    value: "512Mi"
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/BCAT.git
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: true
    value: develop
