name: BCAT build and deploy to OpenShift

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.pipeline
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: build BCAT app
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN}} --server=${{ secrets.OPENSHIFT_SERVER_URL }}
          npm ci
          DEBUG=* npm run build -- --pr=${{ github.sha } --git.branch.name=${{github.ref_name}} --git.ref=${{github.ref}}

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: ./.pipeline
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: deploy to dev
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN}} --server=${{ secrets.OPENSHIFT_SERVER_URL }}
          npm ci
          DEBUG=* npm run deploy -- --pr=${{ github.sha } --env=dev --git.branch.name=${{github.ref_name }} --git.ref=${{github.ref}}
