name: BE PR Checks

env:
  GIT_LOCAL_BRANCH: ${{ github.sha }}

on: [pull_request]

jobs:
  be-pr-checks:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Install dependencies
        run: |
          npm install

      - name: Check lint & format
        run: |
          npm run lint
          npm run format:check

      - name: Test build
        run: |
          npm run build
