name: BE PR Checks

env:
  GIT_LOCAL_BRANCH: ${{ github.sha }}

on: [pull_request]

jobs:
  be-pr-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3
        name: checkout

      # - name: Setup pre-reqs
      #   run: |
      #     npm install yarn -g && yarn set version ./.yarn/releases/yarn-3.2.4.cjs
      #   shell: bash

      # - uses: actions/cache@v3
      #   name: Cache yarn
      #   with:
      #     path: api/.yarn/cache
      #     key: ${{ runner.os }}-fe-yarn-${{ hashFiles('api/yarn.lock') }}
      #     restore-keys: ${{ runner.os }}-fe-yarn-${{ hashFiles('api/yarn.lock') }}

      - name: Install dependencies
        run: |
          npm install

      - name: Check lint & format
        run: |
          npm run lint
          npm run format:check

      - name: Test build
        run: |
          npm run build
