name: FE PR Checks

env:
  GIT_LOCAL_BRANCH: ${{ github.sha }}

on: [pull_request]

jobs:
  fe-pr-checks:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci

      - name: Check format
        run: |
          npm run format:check

      - name: Check lint
        run: |
          npm run lint

      - name: Test build
        run: |
          npm run build
