name: FE PR Checks

env:
  GIT_LOCAL_BRANCH: ${{ github.sha }}

on: [pull_request]

jobs:
  fe-pr-checks:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Install dependencies
        run: |
          npm install

      - name: Check format
        run: |
          npm run format:check

      - name: Check lint
        run: |
          npm run lint

      - name: Test build
        run: |
          npm run build
